"""save_schema.py -- standalone POP0.schema loader for the .PoPSavedGame save-format project.

Reads POP0.schema directly via forge/schema_parser.py and exposes the couple of pieces of derived
data pop_save.py actually needs: primitive field widths and one real, validated schema correction.
"""
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.join(_HERE, 'forge'))
import schema_parser as P

# Pre-extracted (T, names) data, generated by build_cache() below -- same "bake it once into a
# bundled file" pattern as forge_name_registry.json. Lets every consumer of load_schema() run
# without POP0.schema itself present or locatable at all: this project no longer depends on that
# file at runtime, only on this cache. Only needs regenerating if POP0.schema itself changes,
# which for a released retail game is effectively never.
_CACHE_PATH = os.path.join(_HERE, 'schema_cache.json')

# ---- primitive widths by typeIndex (mid byte of the field trailer) ----
# Includes kind=0x11 (id/ref-style scalar, 4 bytes), confirmed against real save-file ground
# truth (PopGameplaySettings.LastPopEnvironmentAreaPortalID).
PRIM_WIDTH = {
    0x00: 1,    # bool / u8
    0x01: 1,    # char/u8
    0x02: 4,
    0x03: 1,    # s8
    0x04: 2,    # s16
    0x05: 2,    # u16
    0x06: 4,    # u32
    0x07: 4,    # u32
    0x09: 8,    # u64
    0x0a: 4,    # float
    0x0b: 8,    # Vector2 (2 floats)
    0x0c: 12,   # Vector3 (3 floats)
    0x0d: 16,   # Vector4 (4 floats)
    0x0e: 16,   # Quaternion / IColor (4 floats)
    0x10: 64,   # Matrix (16 floats)
    0x11: 4,    # id/ref-style scalar -- save-format-specific finding, see module docstring
    0x19: 4,    # enum
    0x1f: 8,    # 2x u32
}

SERIALIZE_BIT = 0x2000000       # a field is part of the normal .forge object-graph serialization
SAVE_PERSIST_BIT = 0x8000000    # a field is written to the .PoPSavedGame save file (see
                                 # pop_save.save_persisted_census's docstring for how this was found)

_SCHEMA = None


def _build_schema_tuple(schema_path=None):
    d, filesize, types, extra, names, endp = P.parse(schema_path) if schema_path else P.parse()
    T = {}
    for t in types:
        T[t['A']] = {'parent': t['B'], 'fields': [(fl, nh, th, tr) for (fl, nh, th, tr) in t['fields']]}

    # POPPlayer fix: the schema says Brightness/BrightnessDefault are 4-byte fields, but they're
    # really 1 byte each - with the schema's own kind, the field walk overshoots by exactly 6
    # bytes, and dropping these two to 1 byte fixes it. Matters here since POPPlayer has other
    # save-persisted fields too (Tutorials, Subtitles, ...).
    POPPlayer = 0x6944b2de
    if POPPlayer in T:
        fields = T[POPPlayer]['fields']
        for i, (fl, nh, fth, tr) in enumerate(fields):
            if nh in (0x962bd533, 0xd9a1ab7d):
                fields[i] = (fl, nh, fth, 0x00000)

    return (T, names)


def _to_json_shape(T, names):
    """int-keyed dicts and tuples aren't JSON-native -- hex-string keys (same '%08x' convention
    as forge_name_registry.json) and field tuples become 4-element arrays. Reversed by
    _from_json_shape on load."""
    types_out = {
        '%08x' % th: {'parent': '%08x' % info['parent'],
                      'fields': [[fl, nh, ft, tr] for (fl, nh, ft, tr) in info['fields']]}
        for th, info in T.items()
    }
    names_out = {'%08x' % h: nm for h, nm in names.items()}
    return {'types': types_out, 'names': names_out}


def _from_json_shape(data):
    T = {
        int(th, 16): {'parent': int(info['parent'], 16),
                      'fields': [tuple(f) for f in info['fields']]}
        for th, info in data['types'].items()
    }
    names = {int(h, 16): nm for h, nm in data['names'].items()}
    return (T, names)


def build_cache(schema_path=None):
    """One-time export: parse POP0.schema live and write the derived (T, names) data to
    schema_cache.json. Run this once (see __main__ below); every normal load_schema() call after
    that never touches POP0.schema again."""
    global _SCHEMA
    _SCHEMA = _build_schema_tuple(schema_path)
    T, names = _SCHEMA
    with open(_CACHE_PATH, 'w', encoding='utf-8') as f:
        json.dump(_to_json_shape(T, names), f)
    return _SCHEMA


def load_schema():
    """Returns (T, names). T[typehash] = {'parent': typehash, 'fields': [(flags, name_hash,
    field_typehash, trailer), ...]}. names[hash] = the real string, for any hash (class or field)
    present in POP0.schema's own name table.

    Loads the bundled schema_cache.json if present (the normal case, see build_cache()) --
    only falls back to parsing POP0.schema live if no cache has been built yet."""
    global _SCHEMA
    if _SCHEMA is not None:
        return _SCHEMA
    if os.path.exists(_CACHE_PATH):
        with open(_CACHE_PATH, 'r', encoding='utf-8') as f:
            data = json.load(f)
        _SCHEMA = _from_json_shape(data)
        return _SCHEMA
    _SCHEMA = _build_schema_tuple()
    return _SCHEMA


if __name__ == '__main__':
    T, names = build_cache()
    print('built schema_cache.json: %d types, %d names' % (len(T), len(names)))
